//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot divide by zero!.
        /// </summary>
        internal static string DivideByZeroError {
            get {
                return ResourceManager.GetString("DivideByZeroError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first number: .
        /// </summary>
        internal static string FirstNumber {
            get {
                return ResourceManager.GetString("FirstNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be null or empty..
        /// </summary>
        internal static string InputNullOrEmpty {
            get {
                return ResourceManager.GetString("InputNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input: &apos;{0}&apos; is not a valid number..
        /// </summary>
        internal static string InvalidNumberError {
            get {
                return ResourceManager.GetString("InvalidNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number. (5, 10, 15, 3.14).
        /// </summary>
        internal static string InvalidNumberHelp {
            get {
                return ResourceManager.GetString("InvalidNumberHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation: &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string InvalidOperationError {
            get {
                return ResourceManager.GetString("InvalidOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter one of the following: +, -, *, /..
        /// </summary>
        internal static string InvalidOperationHelp {
            get {
                return ResourceManager.GetString("InvalidOperationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter supported operations: 
        ///+, add 
        ///-, subtract 
        ///*, times 
        ////, divided by:
        ///
        ///.
        /// </summary>
        internal static string OperationChoice {
            get {
                return ResourceManager.GetString("OperationChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the second number:.
        /// </summary>
        internal static string SecondNumber {
            get {
                return ResourceManager.GetString("SecondNumber", resourceCulture);
            }
        }
    }
}
